modLoader="javafml" 
loaderVersion="[47,)" 
license="MIT"

[[mods]] 
modId="tablistextension" 
version="2.0.0"
displayName="TabListExtension"
authors="hexichi"
logoFile="icon.png"
description='''
扩展TAB列表显示功能.\nExtended TAB list display.
'''

[[mixins]]
config="tablistextension.mixins.json"

[[dependencies.tablistextension]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tablistextension]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"